language: php

services:
  - cassandra

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - composer require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source
  - mysql -e 'create database packaged_dal;'
  - mysql -e 'CREATE TABLE `packaged_dal`.`mock_ql_daos` (
                `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                `username` varchar(50) DEFAULT NULL,
                `display` varchar(50) DEFAULT NULL,
                PRIMARY KEY (`id`)
              ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;'

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
