defaults: &defaults
  working_directory: ~/dal
  steps:
    - run: echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - run: apk -U add wget $APK_PACKAGES
    - run: docker-php-ext-install mysqli pdo pdo_mysql
    - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
    - run:
        name: install dockerize
        command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
        environment:
          DOCKERIZE_VERSION: v0.5.0
    - run:
        name: Wait for MySQL
        command: dockerize -wait tcp://localhost:3306 -timeout 1m
    - run:
        name: Wait for Cassandra
        command: dockerize -wait tcp://localhost:9160 -timeout 1m
    - checkout
    - run: php .circleci/.mysql.php
    - run: composer install -n --prefer-dist
    - run: php vendor/phpunit/phpunit/phpunit -c phpunit.xml --log-junit /tmp/test-results/phpunit/junit.xml
    - store_test_results:
        path: /tmp/test-results

version: 2
jobs:
  build-php56:
    <<: *defaults
    docker:
      - image: php:5.6-alpine
        environment:
          APK_PACKAGES: "php5-apcu php5-memcache"
      - image: cassandra:2.1
        environment:
          CASSANDRA_START_RPC: yes
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_HOST: "%"
      - image: memcached:1.4
  build-php70:
    <<: *defaults
    docker:
      - image: php:7.0-alpine
        environment:
          APK_PACKAGES: "php7-apcu php7-memcached"
      - image: cassandra:2.1
        environment:
          CASSANDRA_START_RPC: yes
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_HOST: "%"
      - image: memcached:1.4

workflows:
  version: 2
  build:
    jobs:
      - build-php56
      - build-php70
